const headlineNews = [
  {
    title: "Jalan Sehat Dalam Rangka HUT RI Ke 80",
    desc: "SMK Negeri 4 Tasikmalaya mengadakan kegiatan jalan sehat dalam rangka memperingati Hari Ulang Tahun Republik Indonesia yang ke-80. Kegiatan ini diikuti oleh seluruh siswa, guru, dan staf sekolah.....",
    img: "https://lh3.googleusercontent.com/pw/AP1GczNYNn2lImNNgIwMgFJdrP-xre00E4rOEpVdseBnRB4P70fz8G1x2e1IM8M6A_Tywmh4wadSjGMfjVP5CEzBHWd2Q2dOCH-0ryA6vc1BqNHIoGO6T7nn-mbqNmF_vmUZN1xaVoJLdF0GDueI1rilUrlM=w1680-h945-s-no-gm?authuser=0",
    detail:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras leo mauris, semper nec augue a, pharetra imperdiet ipsum. Donec ac pharetra est. Nulla nec pharetra ipsum. Integer aliquam pretium neque, eget sagittis felis faucibus ac. Sed et metus accumsan, aliquet lacus eu, ornare neque. Sed vel lacinia justo, placerat commodo tortor. Morbi congue placerat ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus ut feugiat felis, eget hendrerit tortor. Phasellus eu interdum felis. Aliquam sed dapibus leo, sit amet volutpat mi. Nullam sit amet dolor vel magna tincidunt bibendum. Etiam ut tortor augue. Sed non tellus nunc. Ut sit amet sapien id ipsum mattis faucibus porttitor eu nibh. Aliquam vel felis varius, rutrum velit et, tempus lectus.Proin id auctor mauris. Etiam luctus odio sed augue ornare scelerisque. Sed a malesuada lectus. Sed id turpis eu dolor tincidunt lobortis venenatis eu turpis. Duis feugiat hendrerit libero, sit amet posuere augue dapibus vel. Duis non massa vulputate, mattis augue ac, fermentum ligula. Duis nec eros semper, scelerisque urna quis, volutpat felis. Curabitur et porta leo. Nunc convallis consectetur pellentesque. Integer vitae metus luctus, commodo nunc ac, tincidunt diam. Aliquam sapien tortor, faucibus sit amet aliquam vel, ultricies eget nibh. Praesent id aliquet nisi, ac eleifend mi. Suspendisse varius lorem ipsum, id cursus dui fringilla in. Duis dapibus, mauris et vulputate mattis, diam dui mattis neque, vitae scelerisque eros mi ac tortor. In diam urna, ornare ac auctor quis, euismod et leo. Phasellus vitae enim condimentum augue faucibus porttitor nec ornare lacus. Maecenas et vulputate purus. Integer accumsan lectus nec magna pretium, ut porttitor ipsum pretium. Duis sit amet nisl lacinia, dapibus tortor sit amet, eleifend libero. Integer pharetra auctor pretium. Pellentesque eget urna quis mauris dapibus facilisis. Praesent congue pellentesque est vitae accumsan. Integer vitae ornare dui. Ut commodo est purus, eget aliquet velit pellentesque a. Duis et odio ut felis elementum pretium.",
    publisher: "Admin SMKN 4 Tasikmalaya",
    slug: "jalan-sehat-dalam-rangka-hut-ri-ke-80",
  },
];

const headlineRight = [
  {
    title: "Aksi Ekologi Pada Kegiatan MPLS 2025",
    slug: "aksi-ekologi-mpls-2025",
    img: "../assets/image/berita2.jpg",
    desc: "Aksi ekologi yang dilakukan oleh siswa baru SMK Negeri 4 Tasikmalaya pada kegiatan Masa Pengenalan Lingkungan Sekolah....",
    detail:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras leo mauris, semper nec augue a, pharetra imperdiet ipsum. Donec ac pharetra est. Nulla nec pharetra ipsum. Integer aliquam pretium neque, eget sagittis felis faucibus ac. Sed et metus accumsan, aliquet lacus eu, ornare neque. Sed vel lacinia justo, placerat commodo tortor. Morbi congue placerat ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus ut feugiat felis, eget hendrerit tortor. Phasellus eu interdum felis. Aliquam sed dapibus leo, sit amet volutpat mi. Nullam sit amet dolor vel magna tincidunt bibendum. Etiam ut tortor augue. Sed non tellus nunc. Ut sit amet sapien id ipsum mattis faucibus porttitor eu nibh. Aliquam vel felis varius, rutrum velit et, tempus lectus.Proin id auctor mauris. Etiam luctus odio sed augue ornare scelerisque. Sed a malesuada lectus. Sed id turpis eu dolor tincidunt lobortis venenatis eu turpis. Duis feugiat hendrerit libero, sit amet posuere augue dapibus vel. Duis non massa vulputate, mattis augue ac, fermentum ligula. Duis nec eros semper, scelerisque urna quis, volutpat felis. Curabitur et porta leo. Nunc convallis consectetur pellentesque. Integer vitae metus luctus, commodo nunc ac, tincidunt diam. Aliquam sapien tortor, faucibus sit amet aliquam vel, ultricies eget nibh. Praesent id aliquet nisi, ac eleifend mi. Suspendisse varius lorem ipsum, id cursus dui fringilla in. Duis dapibus, mauris et vulputate mattis, diam dui mattis neque, vitae scelerisque eros mi ac tortor. In diam urna, ornare ac auctor quis, euismod et leo. Phasellus vitae enim condimentum augue faucibus porttitor nec ornare lacus. Maecenas et vulputate purus. Integer accumsan lectus nec magna pretium, ut porttitor ipsum pretium. Duis sit amet nisl lacinia, dapibus tortor sit amet, eleifend libero. Integer pharetra auctor pretium. Pellentesque eget urna quis mauris dapibus facilisis. Praesent congue pellentesque est vitae accumsan. Integer vitae ornare dui. Ut commodo est purus, eget aliquet velit pellentesque a. Duis et odio ut felis elementum pretium.",
    publisher: "Admin SMKN 4 Tasikmalaya",
  },
  {
    title: "Kegiatan MBG Di SMKN 4 Tasikmalaya",
    slug: "kegiatan-mbg",
    img: "../assets/image/berita3.jpg",
    desc: "Kegiatan MBG di SMK Negeri 4 Tasikmalaya berjalan dengan lancar dan sukses....",
    detail:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras leo mauris, semper nec augue a, pharetra imperdiet ipsum. Donec ac pharetra est. Nulla nec pharetra ipsum. Integer aliquam pretium neque, eget sagittis felis faucibus ac. Sed et metus accumsan, aliquet lacus eu, ornare neque. Sed vel lacinia justo, placerat commodo tortor. Morbi congue placerat ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus ut feugiat felis, eget hendrerit tortor. Phasellus eu interdum felis. Aliquam sed dapibus leo, sit amet volutpat mi. Nullam sit amet dolor vel magna tincidunt bibendum. Etiam ut tortor augue. Sed non tellus nunc. Ut sit amet sapien id ipsum mattis faucibus porttitor eu nibh. Aliquam vel felis varius, rutrum velit et, tempus lectus.Proin id auctor mauris. Etiam luctus odio sed augue ornare scelerisque. Sed a malesuada lectus. Sed id turpis eu dolor tincidunt lobortis venenatis eu turpis. Duis feugiat hendrerit libero, sit amet posuere augue dapibus vel. Duis non massa vulputate, mattis augue ac, fermentum ligula. Duis nec eros semper, scelerisque urna quis, volutpat felis. Curabitur et porta leo. Nunc convallis consectetur pellentesque. Integer vitae metus luctus, commodo nunc ac, tincidunt diam. Aliquam sapien tortor, faucibus sit amet aliquam vel, ultricies eget nibh. Praesent id aliquet nisi, ac eleifend mi. Suspendisse varius lorem ipsum, id cursus dui fringilla in. Duis dapibus, mauris et vulputate mattis, diam dui mattis neque, vitae scelerisque eros mi ac tortor. In diam urna, ornare ac auctor quis, euismod et leo. Phasellus vitae enim condimentum augue faucibus porttitor nec ornare lacus. Maecenas et vulputate purus. Integer accumsan lectus nec magna pretium, ut porttitor ipsum pretium. Duis sit amet nisl lacinia, dapibus tortor sit amet, eleifend libero. Integer pharetra auctor pretium. Pellentesque eget urna quis mauris dapibus facilisis. Praesent congue pellentesque est vitae accumsan. Integer vitae ornare dui. Ut commodo est purus, eget aliquet velit pellentesque a. Duis et odio ut felis elementum pretium.",
    publisher: "Admin SMKN 4 Tasikmalaya",
  },
];

const otherNews = [
  {
    title: "Talkshow Dengan Siswa Magang Dari Amerika",
    slug: "talkshow-magang-amerika",
    img: "../assets/image/berita4.jpg",
    desc: "Kegiatan talkshow dengan siswa magang dari Amerika yang dihadiri oleh English Club SMK Negeri 4 Tasikmalaya berjalan dengan....",
    detail:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras leo mauris, semper nec augue a, pharetra imperdiet ipsum. Donec ac pharetra est. Nulla nec pharetra ipsum. Integer aliquam pretium neque, eget sagittis felis faucibus ac. Sed et metus accumsan, aliquet lacus eu, ornare neque. Sed vel lacinia justo, placerat commodo tortor. Morbi congue placerat ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus ut feugiat felis, eget hendrerit tortor. Phasellus eu interdum felis. Aliquam sed dapibus leo, sit amet volutpat mi. Nullam sit amet dolor vel magna tincidunt bibendum. Etiam ut tortor augue. Sed non tellus nunc. Ut sit amet sapien id ipsum mattis faucibus porttitor eu nibh. Aliquam vel felis varius, rutrum velit et, tempus lectus.Proin id auctor mauris. Etiam luctus odio sed augue ornare scelerisque. Sed a malesuada lectus. Sed id turpis eu dolor tincidunt lobortis venenatis eu turpis. Duis feugiat hendrerit libero, sit amet posuere augue dapibus vel. Duis non massa vulputate, mattis augue ac, fermentum ligula. Duis nec eros semper, scelerisque urna quis, volutpat felis. Curabitur et porta leo. Nunc convallis consectetur pellentesque. Integer vitae metus luctus, commodo nunc ac, tincidunt diam. Aliquam sapien tortor, faucibus sit amet aliquam vel, ultricies eget nibh. Praesent id aliquet nisi, ac eleifend mi. Suspendisse varius lorem ipsum, id cursus dui fringilla in. Duis dapibus, mauris et vulputate mattis, diam dui mattis neque, vitae scelerisque eros mi ac tortor. In diam urna, ornare ac auctor quis, euismod et leo. Phasellus vitae enim condimentum augue faucibus porttitor nec ornare lacus. Maecenas et vulputate purus. Integer accumsan lectus nec magna pretium, ut porttitor ipsum pretium. Duis sit amet nisl lacinia, dapibus tortor sit amet, eleifend libero. Integer pharetra auctor pretium. Pellentesque eget urna quis mauris dapibus facilisis. Praesent congue pellentesque est vitae accumsan. Integer vitae ornare dui. Ut commodo est purus, eget aliquet velit pellentesque a. Duis et odio ut felis elementum pretium.",
    publisher: "Admin SMKN 4 Tasikmalaya",
  },
  {
    title: "Pelepasan Siswa/Siswi Kelas XII",
    slug: "pelepasan-siswa-xii",
    img: "../assets/image/berita5.jpg",
    desc: "Acara pelepasan siswa/siswi kelas XII SMK Negeri 4 Tasikmalaya berjalan dengan khidmat dan meriah....",
    detail:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras leo mauris, semper nec augue a, pharetra imperdiet ipsum. Donec ac pharetra est. Nulla nec pharetra ipsum. Integer aliquam pretium neque, eget sagittis felis faucibus ac. Sed et metus accumsan, aliquet lacus eu, ornare neque. Sed vel lacinia justo, placerat commodo tortor. Morbi congue placerat ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus ut feugiat felis, eget hendrerit tortor. Phasellus eu interdum felis. Aliquam sed dapibus leo, sit amet volutpat mi. Nullam sit amet dolor vel magna tincidunt bibendum. Etiam ut tortor augue. Sed non tellus nunc. Ut sit amet sapien id ipsum mattis faucibus porttitor eu nibh. Aliquam vel felis varius, rutrum velit et, tempus lectus.Proin id auctor mauris. Etiam luctus odio sed augue ornare scelerisque. Sed a malesuada lectus. Sed id turpis eu dolor tincidunt lobortis venenatis eu turpis. Duis feugiat hendrerit libero, sit amet posuere augue dapibus vel. Duis non massa vulputate, mattis augue ac, fermentum ligula. Duis nec eros semper, scelerisque urna quis, volutpat felis. Curabitur et porta leo. Nunc convallis consectetur pellentesque. Integer vitae metus luctus, commodo nunc ac, tincidunt diam. Aliquam sapien tortor, faucibus sit amet aliquam vel, ultricies eget nibh. Praesent id aliquet nisi, ac eleifend mi. Suspendisse varius lorem ipsum, id cursus dui fringilla in. Duis dapibus, mauris et vulputate mattis, diam dui mattis neque, vitae scelerisque eros mi ac tortor. In diam urna, ornare ac auctor quis, euismod et leo. Phasellus vitae enim condimentum augue faucibus porttitor nec ornare lacus. Maecenas et vulputate purus. Integer accumsan lectus nec magna pretium, ut porttitor ipsum pretium. Duis sit amet nisl lacinia, dapibus tortor sit amet, eleifend libero. Integer pharetra auctor pretium. Pellentesque eget urna quis mauris dapibus facilisis. Praesent congue pellentesque est vitae accumsan. Integer vitae ornare dui. Ut commodo est purus, eget aliquet velit pellentesque a. Duis et odio ut felis elementum pretium.",
    publisher: "Admin SMKN 4 Tasikmalaya",
  },
  {
    title: "Touring Marcopolo",
    slug: "touring-marcopolo",
    img: "../assets/image/berita6.jpg ",
    desc: "Kegiatan touring marcopolo yang diikuti oleh para guru dan staf di SMK Negeri 4 Tasikmalaya berjalan dengan lancar dan sukses....",
    detail:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras leo mauris, semper nec augue a, pharetra imperdiet ipsum. Donec ac pharetra est. Nulla nec pharetra ipsum. Integer aliquam pretium neque, eget sagittis felis faucibus ac. Sed et metus accumsan, aliquet lacus eu, ornare neque. Sed vel lacinia justo, placerat commodo tortor. Morbi congue placerat ullamcorper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus ut feugiat felis, eget hendrerit tortor. Phasellus eu interdum felis. Aliquam sed dapibus leo, sit amet volutpat mi. Nullam sit amet dolor vel magna tincidunt bibendum. Etiam ut tortor augue. Sed non tellus nunc. Ut sit amet sapien id ipsum mattis faucibus porttitor eu nibh. Aliquam vel felis varius, rutrum velit et, tempus lectus.Proin id auctor mauris. Etiam luctus odio sed augue ornare scelerisque. Sed a malesuada lectus. Sed id turpis eu dolor tincidunt lobortis venenatis eu turpis. Duis feugiat hendrerit libero, sit amet posuere augue dapibus vel. Duis non massa vulputate, mattis augue ac, fermentum ligula. Duis nec eros semper, scelerisque urna quis, volutpat felis. Curabitur et porta leo. Nunc convallis consectetur pellentesque. Integer vitae metus luctus, commodo nunc ac, tincidunt diam. Aliquam sapien tortor, faucibus sit amet aliquam vel, ultricies eget nibh. Praesent id aliquet nisi, ac eleifend mi. Suspendisse varius lorem ipsum, id cursus dui fringilla in. Duis dapibus, mauris et vulputate mattis, diam dui mattis neque, vitae scelerisque eros mi ac tortor. In diam urna, ornare ac auctor quis, euismod et leo. Phasellus vitae enim condimentum augue faucibus porttitor nec ornare lacus. Maecenas et vulputate purus. Integer accumsan lectus nec magna pretium, ut porttitor ipsum pretium. Duis sit amet nisl lacinia, dapibus tortor sit amet, eleifend libero. Integer pharetra auctor pretium. Pellentesque eget urna quis mauris dapibus facilisis. Praesent congue pellentesque est vitae accumsan. Integer vitae ornare dui. Ut commodo est purus, eget aliquet velit pellentesque a. Duis et odio ut felis elementum pretium.",
    publisher: "Admin SMKN 4 Tasikmalaya",
  },
];
